.class public abstract Lcom/vidio/kmm/tracker/plenty/event/Screen;
.super Ljava/lang/Object;
.source "SourceFile"

# interfaces
.implements Landroid/os/Parcelable;


# annotations
.annotation system Ldalvik/annotation/MemberClasses;
    value = {
        Lcom/vidio/kmm/tracker/plenty/event/Screen$Account;,
        Lcom/vidio/kmm/tracker/plenty/event/Screen$AccountEmail;,
        Lcom/vidio/kmm/tracker/plenty/event/Screen$AccountMobileNumber;,
        Lcom/vidio/kmm/tracker/plenty/event/Screen$AccountPassword;,
        Lcom/vidio/kmm/tracker/plenty/event/Screen$AccountSettings;,
        Lcom/vidio/kmm/tracker/plenty/event/Screen$AfterPaid;,
        Lcom/vidio/kmm/tracker/plenty/event/Screen$AgeGender;,
        Lcom/vidio/kmm/tracker/plenty/event/Screen$CancelRecurringFeedbackForm;,
        Lcom/vidio/kmm/tracker/plenty/event/Screen$CancelSubscriptionBenefits;,
        Lcom/vidio/kmm/tracker/plenty/event/Screen$Category;,
        Lcom/vidio/kmm/tracker/plenty/event/Screen$CategoryIndex;,
        Lcom/vidio/kmm/tracker/plenty/event/Screen$Checkout;,
        Lcom/vidio/kmm/tracker/plenty/event/Screen$ConnectToTV;,
        Lcom/vidio/kmm/tracker/plenty/event/Screen$ContentProfile;,
        Lcom/vidio/kmm/tracker/plenty/event/Screen$ContentScheduleSports;,
        Lcom/vidio/kmm/tracker/plenty/event/Screen$ContentScheduleTV;,
        Lcom/vidio/kmm/tracker/plenty/event/Screen$ContentTag;,
        Lcom/vidio/kmm/tracker/plenty/event/Screen$CreateProfile;,
        Lcom/vidio/kmm/tracker/plenty/event/Screen$Download;,
        Lcom/vidio/kmm/tracker/plenty/event/Screen$EditProfile;,
        Lcom/vidio/kmm/tracker/plenty/event/Screen$Empty;,
        Lcom/vidio/kmm/tracker/plenty/event/Screen$ExpiredSubscriptionDetail;,
        Lcom/vidio/kmm/tracker/plenty/event/Screen$Feedback;,
        Lcom/vidio/kmm/tracker/plenty/event/Screen$Feeds;,
        Lcom/vidio/kmm/tracker/plenty/event/Screen$Following;,
        Lcom/vidio/kmm/tracker/plenty/event/Screen$ForgotPassword;,
        Lcom/vidio/kmm/tracker/plenty/event/Screen$Games;,
        Lcom/vidio/kmm/tracker/plenty/event/Screen$GroupChatIndex;,
        Lcom/vidio/kmm/tracker/plenty/event/Screen$GroupChatInfo;,
        Lcom/vidio/kmm/tracker/plenty/event/Screen$GroupChatNewGroup;,
        Lcom/vidio/kmm/tracker/plenty/event/Screen$GroupChatRoom;,
        Lcom/vidio/kmm/tracker/plenty/event/Screen$GroupInfoEditGroup;,
        Lcom/vidio/kmm/tracker/plenty/event/Screen$Home;,
        Lcom/vidio/kmm/tracker/plenty/event/Screen$KidsBlocker;,
        Lcom/vidio/kmm/tracker/plenty/event/Screen$LiveIndex;,
        Lcom/vidio/kmm/tracker/plenty/event/Screen$LivestreamingWatchpage;,
        Lcom/vidio/kmm/tracker/plenty/event/Screen$Login;,
        Lcom/vidio/kmm/tracker/plenty/event/Screen$MultiProfileLogin;,
        Lcom/vidio/kmm/tracker/plenty/event/Screen$MyList;,
        Lcom/vidio/kmm/tracker/plenty/event/Screen$MySubscription;,
        Lcom/vidio/kmm/tracker/plenty/event/Screen$NetworkDiagnostic;,
        Lcom/vidio/kmm/tracker/plenty/event/Screen$Notification;,
        Lcom/vidio/kmm/tracker/plenty/event/Screen$OTPVerification;,
        Lcom/vidio/kmm/tracker/plenty/event/Screen$OnboardingWalkthrough;,
        Lcom/vidio/kmm/tracker/plenty/event/Screen$Payment;,
        Lcom/vidio/kmm/tracker/plenty/event/Screen$PaymentFailed;,
        Lcom/vidio/kmm/tracker/plenty/event/Screen$Paywall;,
        Lcom/vidio/kmm/tracker/plenty/event/Screen$ProfileSelection;,
        Lcom/vidio/kmm/tracker/plenty/event/Screen$ProfileUser;,
        Lcom/vidio/kmm/tracker/plenty/event/Screen$QRScanner;,
        Lcom/vidio/kmm/tracker/plenty/event/Screen$RecommendationDownload;,
        Lcom/vidio/kmm/tracker/plenty/event/Screen$Registration;,
        Lcom/vidio/kmm/tracker/plenty/event/Screen$Rental;,
        Lcom/vidio/kmm/tracker/plenty/event/Screen$Search;,
        Lcom/vidio/kmm/tracker/plenty/event/Screen$SearchResult;,
        Lcom/vidio/kmm/tracker/plenty/event/Screen$SearchResultCollections;,
        Lcom/vidio/kmm/tracker/plenty/event/Screen$SearchResultLives;,
        Lcom/vidio/kmm/tracker/plenty/event/Screen$SearchResultMoviesSeries;,
        Lcom/vidio/kmm/tracker/plenty/event/Screen$SearchResultUsers;,
        Lcom/vidio/kmm/tracker/plenty/event/Screen$SearchResultVideos;,
        Lcom/vidio/kmm/tracker/plenty/event/Screen$SectionDetail;,
        Lcom/vidio/kmm/tracker/plenty/event/Screen$Settings;,
        Lcom/vidio/kmm/tracker/plenty/event/Screen$ShortIndex;,
        Lcom/vidio/kmm/tracker/plenty/event/Screen$Shorts;,
        Lcom/vidio/kmm/tracker/plenty/event/Screen$TVActivePackage;,
        Lcom/vidio/kmm/tracker/plenty/event/Screen$TVBlocker;,
        Lcom/vidio/kmm/tracker/plenty/event/Screen$TVCancelPackage;,
        Lcom/vidio/kmm/tracker/plenty/event/Screen$TVCheckout;,
        Lcom/vidio/kmm/tracker/plenty/event/Screen$TVCodeLogin;,
        Lcom/vidio/kmm/tracker/plenty/event/Screen$TVConnectAccount;,
        Lcom/vidio/kmm/tracker/plenty/event/Screen$TVEpisodeList;,
        Lcom/vidio/kmm/tracker/plenty/event/Screen$TVGetPremier;,
        Lcom/vidio/kmm/tracker/plenty/event/Screen$TVLive;,
        Lcom/vidio/kmm/tracker/plenty/event/Screen$TVLivestreamWatchpage;,
        Lcom/vidio/kmm/tracker/plenty/event/Screen$TVLogin;,
        Lcom/vidio/kmm/tracker/plenty/event/Screen$TVLoginPage;,
        Lcom/vidio/kmm/tracker/plenty/event/Screen$TVManageSubs;,
        Lcom/vidio/kmm/tracker/plenty/event/Screen$TVMovieProfile;,
        Lcom/vidio/kmm/tracker/plenty/event/Screen$TVOEMLoginGatingBanner;,
        Lcom/vidio/kmm/tracker/plenty/event/Screen$TVPackageInfo;,
        Lcom/vidio/kmm/tracker/plenty/event/Screen$TVPage;,
        Lcom/vidio/kmm/tracker/plenty/event/Screen$TVPayment;,
        Lcom/vidio/kmm/tracker/plenty/event/Screen$TVProductCatalogList;,
        Lcom/vidio/kmm/tracker/plenty/event/Screen$TVProfile;,
        Lcom/vidio/kmm/tracker/plenty/event/Screen$TVReminderUpdate;,
        Lcom/vidio/kmm/tracker/plenty/event/Screen$TVScheduleURL;,
        Lcom/vidio/kmm/tracker/plenty/event/Screen$TVSearchPage;,
        Lcom/vidio/kmm/tracker/plenty/event/Screen$TVSearchResult;,
        Lcom/vidio/kmm/tracker/plenty/event/Screen$TVUpcoming;,
        Lcom/vidio/kmm/tracker/plenty/event/Screen$TVVidioAppQRDownload;,
        Lcom/vidio/kmm/tracker/plenty/event/Screen$TVViewMode;,
        Lcom/vidio/kmm/tracker/plenty/event/Screen$TVWatchList;,
        Lcom/vidio/kmm/tracker/plenty/event/Screen$TagCollection;,
        Lcom/vidio/kmm/tracker/plenty/event/Screen$TagLivestreaming;,
        Lcom/vidio/kmm/tracker/plenty/event/Screen$TagVideo;,
        Lcom/vidio/kmm/tracker/plenty/event/Screen$TransactionHistoriesPackageDetails;,
        Lcom/vidio/kmm/tracker/plenty/event/Screen$TransactionList;,
        Lcom/vidio/kmm/tracker/plenty/event/Screen$TransactionSuccess;,
        Lcom/vidio/kmm/tracker/plenty/event/Screen$UpcomingPage;,
        Lcom/vidio/kmm/tracker/plenty/event/Screen$UserOnboardingContentPreferences;,
        Lcom/vidio/kmm/tracker/plenty/event/Screen$UserRegistration;,
        Lcom/vidio/kmm/tracker/plenty/event/Screen$VODWatchPage;,
        Lcom/vidio/kmm/tracker/plenty/event/Screen$ViewingRestrictions;,
        Lcom/vidio/kmm/tracker/plenty/event/Screen$WatchHistory;,
        Lcom/vidio/kmm/tracker/plenty/event/Screen$WatchList;,
        Lcom/vidio/kmm/tracker/plenty/event/Screen$WelcomePage;
    }
.end annotation

.annotation runtime Lkotlin/Metadata;
    d1 = {
        "\u0000\u00be\u0003\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\u0008j\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0000\u00087\u0018\u00002\u00060\u0001j\u0002`\u0002:j\u0003\u0004\u0005\u0006\u0007\u0008\t\n\u000b\u000c\r\u000e\u000f\u0010\u0011\u0012\u0013\u0014\u0015\u0016\u0017\u0018\u0019\u001a\u001b\u001c\u001d\u001e\u001f !\"#$%&\'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_`abcdefghijkl\u0082\u0001\u00c3\u0001mnopqrstuvwxyz{|}~\u007f\u0080\u0001\u0081\u0001\u0082\u0001\u0083\u0001\u0084\u0001\u0085\u0001\u0086\u0001\u0087\u0001\u0088\u0001\u0089\u0001\u008a\u0001\u008b\u0001\u008c\u0001\u008d\u0001\u008e\u0001\u008f\u0001\u0090\u0001\u0091\u0001\u0092\u0001\u0093\u0001\u0094\u0001\u0095\u0001\u0096\u0001\u0097\u0001\u0098\u0001\u0099\u0001\u009a\u0001\u009b\u0001\u009c\u0001\u009d\u0001\u009e\u0001\u009f\u0001\u00a0\u0001\u00a1\u0001\u00a2\u0001\u00a3\u0001\u00a4\u0001\u00a5\u0001\u00a6\u0001\u00a7\u0001\u00a8\u0001\u00a9\u0001\u00aa\u0001\u00ab\u0001\u00ac\u0001\u00ad\u0001\u00ae\u0001\u00af\u0001\u00b0\u0001\u00b1\u0001\u00b2\u0001\u00b3\u0001\u00b4\u0001\u00b5\u0001\u00b6\u0001\u00b7\u0001\u00b8\u0001\u00b9\u0001\u00ba\u0001\u00bb\u0001\u00bc\u0001\u00bd\u0001\u00be\u0001\u00bf\u0001\u00c0\u0001\u00c1\u0001\u00c2\u0001\u00c3\u0001\u00c4\u0001\u00c5\u0001\u00c6\u0001\u00c7\u0001\u00c8\u0001\u00c9\u0001\u00ca\u0001\u00cb\u0001\u00cc\u0001\u00cd\u0001\u00ce\u0001\u00cf\u0001\u00d0\u0001\u00d1\u0001\u00d2\u0001\u00d3\u0001\u00d4\u0001\u00d5\u0001\u00d6\u0001\u00d7\u0001\u00a8\u0006\u00d8\u0001"
    }
    d2 = {
        "Lcom/vidio/kmm/tracker/plenty/event/Screen;",
        "Landroid/os/Parcelable;",
        "Lcom/vidio/kmm/AndroidParcelable;",
        "Empty",
        "Account",
        "AccountSettings",
        "AccountEmail",
        "AccountMobileNumber",
        "AccountPassword",
        "AfterPaid",
        "AgeGender",
        "CancelSubscriptionBenefits",
        "CancelRecurringFeedbackForm",
        "Category",
        "CategoryIndex",
        "Checkout",
        "ConnectToTV",
        "ContentScheduleTV",
        "ContentScheduleSports",
        "ContentProfile",
        "ContentTag",
        "Download",
        "ExpiredSubscriptionDetail",
        "Feedback",
        "Feeds",
        "Following",
        "ForgotPassword",
        "GroupChatIndex",
        "GroupChatNewGroup",
        "GroupChatRoom",
        "GroupChatInfo",
        "GroupInfoEditGroup",
        "Games",
        "Home",
        "LiveIndex",
        "LivestreamingWatchpage",
        "Login",
        "MyList",
        "MySubscription",
        "NetworkDiagnostic",
        "Notification",
        "OTPVerification",
        "OnboardingWalkthrough",
        "Payment",
        "PaymentFailed",
        "Paywall",
        "ProfileUser",
        "QRScanner",
        "RecommendationDownload",
        "Rental",
        "Registration",
        "Search",
        "SearchResult",
        "SearchResultVideos",
        "SearchResultLives",
        "SearchResultUsers",
        "SearchResultCollections",
        "SearchResultMoviesSeries",
        "SectionDetail",
        "Settings",
        "Shorts",
        "ShortIndex",
        "TagCollection",
        "TagLivestreaming",
        "TagVideo",
        "TransactionHistoriesPackageDetails",
        "TransactionList",
        "TransactionSuccess",
        "UpcomingPage",
        "UserRegistration",
        "UserOnboardingContentPreferences",
        "ViewingRestrictions",
        "VODWatchPage",
        "WatchHistory",
        "WatchList",
        "WelcomePage",
        "KidsBlocker",
        "ProfileSelection",
        "CreateProfile",
        "EditProfile",
        "MultiProfileLogin",
        "TVBlocker",
        "TVActivePackage",
        "TVCancelPackage",
        "TVCheckout",
        "TVCodeLogin",
        "TVEpisodeList",
        "TVGetPremier",
        "TVLive",
        "TVLivestreamWatchpage",
        "TVLogin",
        "TVLoginPage",
        "TVManageSubs",
        "TVMovieProfile",
        "TVOEMLoginGatingBanner",
        "TVConnectAccount",
        "TVPackageInfo",
        "TVPage",
        "TVPayment",
        "TVProductCatalogList",
        "TVProfile",
        "TVReminderUpdate",
        "TVScheduleURL",
        "TVSearchPage",
        "TVSearchResult",
        "TVUpcoming",
        "TVVidioAppQRDownload",
        "TVViewMode",
        "TVWatchList",
        "Lcom/vidio/kmm/tracker/plenty/event/Referrer$Main;",
        "Lcom/vidio/kmm/tracker/plenty/event/Screen$Account;",
        "Lcom/vidio/kmm/tracker/plenty/event/Screen$AccountEmail;",
        "Lcom/vidio/kmm/tracker/plenty/event/Screen$AccountMobileNumber;",
        "Lcom/vidio/kmm/tracker/plenty/event/Screen$AccountPassword;",
        "Lcom/vidio/kmm/tracker/plenty/event/Screen$AccountSettings;",
        "Lcom/vidio/kmm/tracker/plenty/event/Screen$AfterPaid;",
        "Lcom/vidio/kmm/tracker/plenty/event/Screen$AgeGender;",
        "Lcom/vidio/kmm/tracker/plenty/event/Screen$CancelRecurringFeedbackForm;",
        "Lcom/vidio/kmm/tracker/plenty/event/Screen$CancelSubscriptionBenefits;",
        "Lcom/vidio/kmm/tracker/plenty/event/Screen$Category;",
        "Lcom/vidio/kmm/tracker/plenty/event/Screen$CategoryIndex;",
        "Lcom/vidio/kmm/tracker/plenty/event/Screen$Checkout;",
        "Lcom/vidio/kmm/tracker/plenty/event/Screen$ConnectToTV;",
        "Lcom/vidio/kmm/tracker/plenty/event/Screen$ContentProfile;",
        "Lcom/vidio/kmm/tracker/plenty/event/Screen$ContentScheduleSports;",
        "Lcom/vidio/kmm/tracker/plenty/event/Screen$ContentScheduleTV;",
        "Lcom/vidio/kmm/tracker/plenty/event/Screen$ContentTag;",
        "Lcom/vidio/kmm/tracker/plenty/event/Screen$CreateProfile;",
        "Lcom/vidio/kmm/tracker/plenty/event/Screen$Download;",
        "Lcom/vidio/kmm/tracker/plenty/event/Screen$EditProfile;",
        "Lcom/vidio/kmm/tracker/plenty/event/Screen$Empty;",
        "Lcom/vidio/kmm/tracker/plenty/event/Screen$ExpiredSubscriptionDetail;",
        "Lcom/vidio/kmm/tracker/plenty/event/Screen$Feedback;",
        "Lcom/vidio/kmm/tracker/plenty/event/Screen$Feeds;",
        "Lcom/vidio/kmm/tracker/plenty/event/Screen$Following;",
        "Lcom/vidio/kmm/tracker/plenty/event/Screen$ForgotPassword;",
        "Lcom/vidio/kmm/tracker/plenty/event/Screen$Games;",
        "Lcom/vidio/kmm/tracker/plenty/event/Screen$GroupChatIndex;",
        "Lcom/vidio/kmm/tracker/plenty/event/Screen$GroupChatInfo;",
        "Lcom/vidio/kmm/tracker/plenty/event/Screen$GroupChatNewGroup;",
        "Lcom/vidio/kmm/tracker/plenty/event/Screen$GroupChatRoom;",
        "Lcom/vidio/kmm/tracker/plenty/event/Screen$GroupInfoEditGroup;",
        "Lcom/vidio/kmm/tracker/plenty/event/Screen$Home;",
        "Lcom/vidio/kmm/tracker/plenty/event/Screen$KidsBlocker;",
        "Lcom/vidio/kmm/tracker/plenty/event/Screen$LiveIndex;",
        "Lcom/vidio/kmm/tracker/plenty/event/Screen$LivestreamingWatchpage;",
        "Lcom/vidio/kmm/tracker/plenty/event/Screen$Login;",
        "Lcom/vidio/kmm/tracker/plenty/event/Screen$MultiProfileLogin;",
        "Lcom/vidio/kmm/tracker/plenty/event/Screen$MyList;",
        "Lcom/vidio/kmm/tracker/plenty/event/Screen$MySubscription;",
        "Lcom/vidio/kmm/tracker/plenty/event/Screen$NetworkDiagnostic;",
        "Lcom/vidio/kmm/tracker/plenty/event/Screen$Notification;",
        "Lcom/vidio/kmm/tracker/plenty/event/Screen$OTPVerification;",
        "Lcom/vidio/kmm/tracker/plenty/event/Screen$OnboardingWalkthrough;",
        "Lcom/vidio/kmm/tracker/plenty/event/Screen$Payment;",
        "Lcom/vidio/kmm/tracker/plenty/event/Screen$PaymentFailed;",
        "Lcom/vidio/kmm/tracker/plenty/event/Screen$Paywall;",
        "Lcom/vidio/kmm/tracker/plenty/event/Screen$ProfileSelection;",
        "Lcom/vidio/kmm/tracker/plenty/event/Screen$ProfileUser;",
        "Lcom/vidio/kmm/tracker/plenty/event/Screen$QRScanner;",
        "Lcom/vidio/kmm/tracker/plenty/event/Screen$RecommendationDownload;",
        "Lcom/vidio/kmm/tracker/plenty/event/Screen$Registration;",
        "Lcom/vidio/kmm/tracker/plenty/event/Screen$Rental;",
        "Lcom/vidio/kmm/tracker/plenty/event/Screen$Search;",
        "Lcom/vidio/kmm/tracker/plenty/event/Screen$SearchResult;",
        "Lcom/vidio/kmm/tracker/plenty/event/Screen$SearchResultCollections;",
        "Lcom/vidio/kmm/tracker/plenty/event/Screen$SearchResultLives;",
        "Lcom/vidio/kmm/tracker/plenty/event/Screen$SearchResultMoviesSeries;",
        "Lcom/vidio/kmm/tracker/plenty/event/Screen$SearchResultUsers;",
        "Lcom/vidio/kmm/tracker/plenty/event/Screen$SearchResultVideos;",
        "Lcom/vidio/kmm/tracker/plenty/event/Screen$SectionDetail;",
        "Lcom/vidio/kmm/tracker/plenty/event/Screen$Settings;",
        "Lcom/vidio/kmm/tracker/plenty/event/Screen$ShortIndex;",
        "Lcom/vidio/kmm/tracker/plenty/event/Screen$Shorts;",
        "Lcom/vidio/kmm/tracker/plenty/event/Screen$TVActivePackage;",
        "Lcom/vidio/kmm/tracker/plenty/event/Screen$TVBlocker;",
        "Lcom/vidio/kmm/tracker/plenty/event/Screen$TVCancelPackage;",
        "Lcom/vidio/kmm/tracker/plenty/event/Screen$TVCheckout;",
        "Lcom/vidio/kmm/tracker/plenty/event/Screen$TVCodeLogin;",
        "Lcom/vidio/kmm/tracker/plenty/event/Screen$TVConnectAccount;",
        "Lcom/vidio/kmm/tracker/plenty/event/Screen$TVEpisodeList;",
        "Lcom/vidio/kmm/tracker/plenty/event/Screen$TVGetPremier;",
        "Lcom/vidio/kmm/tracker/plenty/event/Screen$TVLive;",
        "Lcom/vidio/kmm/tracker/plenty/event/Screen$TVLivestreamWatchpage;",
        "Lcom/vidio/kmm/tracker/plenty/event/Screen$TVLogin;",
        "Lcom/vidio/kmm/tracker/plenty/event/Screen$TVLoginPage;",
        "Lcom/vidio/kmm/tracker/plenty/event/Screen$TVManageSubs;",
        "Lcom/vidio/kmm/tracker/plenty/event/Screen$TVMovieProfile;",
        "Lcom/vidio/kmm/tracker/plenty/event/Screen$TVOEMLoginGatingBanner;",
        "Lcom/vidio/kmm/tracker/plenty/event/Screen$TVPackageInfo;",
        "Lcom/vidio/kmm/tracker/plenty/event/Screen$TVPage;",
        "Lcom/vidio/kmm/tracker/plenty/event/Screen$TVPayment;",
        "Lcom/vidio/kmm/tracker/plenty/event/Screen$TVProductCatalogList;",
        "Lcom/vidio/kmm/tracker/plenty/event/Screen$TVProfile;",
        "Lcom/vidio/kmm/tracker/plenty/event/Screen$TVReminderUpdate;",
        "Lcom/vidio/kmm/tracker/plenty/event/Screen$TVScheduleURL;",
        "Lcom/vidio/kmm/tracker/plenty/event/Screen$TVSearchPage;",
        "Lcom/vidio/kmm/tracker/plenty/event/Screen$TVSearchResult;",
        "Lcom/vidio/kmm/tracker/plenty/event/Screen$TVUpcoming;",
        "Lcom/vidio/kmm/tracker/plenty/event/Screen$TVVidioAppQRDownload;",
        "Lcom/vidio/kmm/tracker/plenty/event/Screen$TVViewMode;",
        "Lcom/vidio/kmm/tracker/plenty/event/Screen$TVWatchList;",
        "Lcom/vidio/kmm/tracker/plenty/event/Screen$TagCollection;",
        "Lcom/vidio/kmm/tracker/plenty/event/Screen$TagLivestreaming;",
        "Lcom/vidio/kmm/tracker/plenty/event/Screen$TagVideo;",
        "Lcom/vidio/kmm/tracker/plenty/event/Screen$TransactionHistoriesPackageDetails;",
        "Lcom/vidio/kmm/tracker/plenty/event/Screen$TransactionList;",
        "Lcom/vidio/kmm/tracker/plenty/event/Screen$TransactionSuccess;",
        "Lcom/vidio/kmm/tracker/plenty/event/Screen$UpcomingPage;",
        "Lcom/vidio/kmm/tracker/plenty/event/Screen$UserOnboardingContentPreferences;",
        "Lcom/vidio/kmm/tracker/plenty/event/Screen$UserRegistration;",
        "Lcom/vidio/kmm/tracker/plenty/event/Screen$VODWatchPage;",
        "Lcom/vidio/kmm/tracker/plenty/event/Screen$ViewingRestrictions;",
        "Lcom/vidio/kmm/tracker/plenty/event/Screen$WatchHistory;",
        "Lcom/vidio/kmm/tracker/plenty/event/Screen$WatchList;",
        "Lcom/vidio/kmm/tracker/plenty/event/Screen$WelcomePage;",
        "shared"
    }
    k = 0x1
    mv = {
        0x2,
        0x2,
        0x0
    }
    xi = 0x30
.end annotation


# instance fields
.field private final c:Ljava/lang/String;
    .annotation build Lorg/jetbrains/annotations/NotNull;
    .end annotation
.end field


# direct methods
.method public constructor <init>(Ljava/lang/String;)V
    .locals 0

    .line 1
    invoke-direct {p0}, Ljava/lang/Object;-><init>()V

    .line 2
    .line 3
    .line 4
    iput-object p1, p0, Lcom/vidio/kmm/tracker/plenty/event/Screen;->c:Ljava/lang/String;

    .line 5
    .line 6
    return-void
.end method


# virtual methods
.method public final a()Ljava/lang/String;
    .locals 1
    .annotation build Lorg/jetbrains/annotations/NotNull;
    .end annotation

    .line 1
    iget-object v0, p0, Lcom/vidio/kmm/tracker/plenty/event/Screen;->c:Ljava/lang/String;

    .line 2
    .line 3
    return-object v0
.end method
