package com.google.android.gms.internal.pal;

import java.net.InetAddress;
import java.net.URI;
import java.net.URL;
import java.util.BitSet;
import java.util.Calendar;
import java.util.Currency;
import java.util.GregorianCalendar;
import java.util.Locale;
import java.util.UUID;
import java.util.concurrent.atomic.AtomicBoolean;
import java.util.concurrent.atomic.AtomicInteger;
import java.util.concurrent.atomic.AtomicIntegerArray;

/* loaded from: classes4.dex */
public final class zzaba {
    public static final zzzg zzA;
    public static final zzzg zzB;
    public static final zzzh zzC;
    public static final zzzg zzD;
    public static final zzzh zzE;
    public static final zzzg zzF;
    public static final zzzh zzG;
    public static final zzzg zzH;
    public static final zzzh zzI;
    public static final zzzg zzJ;
    public static final zzzh zzK;
    public static final zzzg zzL;
    public static final zzzh zzM;
    public static final zzzg zzN;
    public static final zzzh zzO;
    public static final zzzg zzP;
    public static final zzzh zzQ;
    public static final zzzg zzR;
    public static final zzzh zzS;
    public static final zzzg zzT;
    public static final zzzh zzU;
    public static final zzzg zzV;
    public static final zzzh zzW;
    public static final zzzh zzX;
    public static final zzzg zza;
    public static final zzzh zzb;
    public static final zzzg zzc;
    public static final zzzh zzd;
    public static final zzzg zze;
    public static final zzzg zzf;
    public static final zzzh zzg;
    public static final zzzg zzh;
    public static final zzzh zzi;
    public static final zzzg zzj;
    public static final zzzh zzk;
    public static final zzzg zzl;
    public static final zzzh zzm;
    public static final zzzg zzn;
    public static final zzzh zzo;
    public static final zzzg zzp;
    public static final zzzh zzq;
    public static final zzzg zzr;
    public static final zzzh zzs;
    public static final zzzg zzt;
    public static final zzzg zzu;
    public static final zzzg zzv;
    public static final zzzg zzw;
    public static final zzzh zzx;
    public static final zzzg zzy;
    public static final zzzg zzz;

    static {
        zzzg zzc2 = new zzaad().zzc();
        zza = zzc2;
        zzb = new zzaap(Class.class, zzc2);
        zzzg zzc3 = new zzaao().zzc();
        zzc = zzc3;
        zzd = new zzaap(BitSet.class, zzc3);
        zzaat zzaatVar = new zzaat();
        zze = zzaatVar;
        zzf = new zzaau();
        zzg = new zzaaq(Boolean.TYPE, Boolean.class, zzaatVar);
        zzaav zzaavVar = new zzaav();
        zzh = zzaavVar;
        zzi = new zzaaq(Byte.TYPE, Byte.class, zzaavVar);
        zzaaw zzaawVar = new zzaaw();
        zzj = zzaawVar;
        zzk = new zzaaq(Short.TYPE, Short.class, zzaawVar);
        zzaax zzaaxVar = new zzaax();
        zzl = zzaaxVar;
        zzm = new zzaaq(Integer.TYPE, Integer.class, zzaaxVar);
        zzzg zzc4 = new zzaay().zzc();
        zzn = zzc4;
        zzo = new zzaap(AtomicInteger.class, zzc4);
        zzzg zzc5 = new zzaaz().zzc();
        zzp = zzc5;
        zzq = new zzaap(AtomicBoolean.class, zzc5);
        zzzg zzc6 = new zzzt().zzc();
        zzr = zzc6;
        zzs = new zzaap(AtomicIntegerArray.class, zzc6);
        zzt = new zzzu();
        zzu = new zzzv();
        zzv = new zzzw();
        zzzx zzzxVar = new zzzx();
        zzw = zzzxVar;
        zzx = new zzaaq(Character.TYPE, Character.class, zzzxVar);
        zzzy zzzyVar = new zzzy();
        zzy = zzzyVar;
        zzz = new zzzz();
        zzA = new zzaaa();
        zzB = new zzaab();
        zzC = new zzaap(String.class, zzzyVar);
        zzaac zzaacVar = new zzaac();
        zzD = zzaacVar;
        zzE = new zzaap(StringBuilder.class, zzaacVar);
        zzaae zzaaeVar = new zzaae();
        zzF = zzaaeVar;
        zzG = new zzaap(StringBuffer.class, zzaaeVar);
        zzaaf zzaafVar = new zzaaf();
        zzH = zzaafVar;
        zzI = new zzaap(URL.class, zzaafVar);
        zzaag zzaagVar = new zzaag();
        zzJ = zzaagVar;
        zzK = new zzaap(URI.class, zzaagVar);
        zzaah zzaahVar = new zzaah();
        zzL = zzaahVar;
        zzM = new zzaas(InetAddress.class, zzaahVar);
        zzaai zzaaiVar = new zzaai();
        zzN = zzaaiVar;
        zzO = new zzaap(UUID.class, zzaaiVar);
        zzzg zzc7 = new zzaaj().zzc();
        zzP = zzc7;
        zzQ = new zzaap(Currency.class, zzc7);
        zzaak zzaakVar = new zzaak();
        zzR = zzaakVar;
        zzS = new zzaar(Calendar.class, GregorianCalendar.class, zzaakVar);
        zzaal zzaalVar = new zzaal();
        zzT = zzaalVar;
        zzU = new zzaap(Locale.class, zzaalVar);
        zzaam zzaamVar = new zzaam();
        zzV = zzaamVar;
        zzW = new zzaas(zzyy.class, zzaamVar);
        zzX = new zzaan();
    }
}
