package com.amazonaws.regions;

import com.amazonaws.services.s3.internal.Constants;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;

/* JADX INFO: Access modifiers changed from: package-private */
/* loaded from: classes.dex */
public class RegionDefaults {
    RegionDefaults() {
    }

    public static List<Region> a() {
        ArrayList arrayList = new ArrayList();
        Region region = new Region("af-south-1", "amazonaws.com");
        arrayList.add(region);
        b(region, ServiceAbbreviations.f21145p, "autoscaling.af-south-1.amazonaws.com", false, true);
        b(region, ServiceAbbreviations.f21134e, "dynamodb.af-south-1.amazonaws.com", false, true);
        b(region, ServiceAbbreviations.f21135f, "ec2.af-south-1.amazonaws.com", false, true);
        b(region, ServiceAbbreviations.f21151v, "elasticloadbalancing.af-south-1.amazonaws.com", false, true);
        b(region, "kms", "kms.af-south-1.amazonaws.com", false, true);
        b(region, "lambda", "lambda.af-south-1.amazonaws.com", false, true);
        b(region, "logs", "logs.af-south-1.amazonaws.com", false, true);
        b(region, "s3", "s3.af-south-1.amazonaws.com", false, true);
        b(region, ServiceAbbreviations.f21142m, "sns.af-south-1.amazonaws.com", false, true);
        b(region, ServiceAbbreviations.f21143n, "sqs.af-south-1.amazonaws.com", false, true);
        b(region, ServiceAbbreviations.f21149t, "sts.af-south-1.amazonaws.com", false, true);
        Region region2 = new Region("ap-northeast-1", "amazonaws.com");
        arrayList.add(region2);
        b(region2, ServiceAbbreviations.f21145p, "autoscaling.ap-northeast-1.amazonaws.com", false, true);
        b(region2, "cognito-identity", "cognito-identity.ap-northeast-1.amazonaws.com", false, true);
        b(region2, "cognito-idp", "cognito-idp.ap-northeast-1.amazonaws.com", false, true);
        b(region2, "cognito-sync", "cognito-sync.ap-northeast-1.amazonaws.com", false, true);
        b(region2, "data.iot", "data.iot.ap-northeast-1.amazonaws.com", false, true);
        b(region2, ServiceAbbreviations.f21134e, "dynamodb.ap-northeast-1.amazonaws.com", false, true);
        b(region2, ServiceAbbreviations.f21135f, "ec2.ap-northeast-1.amazonaws.com", false, true);
        b(region2, ServiceAbbreviations.f21151v, "elasticloadbalancing.ap-northeast-1.amazonaws.com", false, true);
        b(region2, "firehose", "firehose.ap-northeast-1.amazonaws.com", false, true);
        b(region2, "iot", "iot.ap-northeast-1.amazonaws.com", false, true);
        b(region2, "kinesis", "kinesis.ap-northeast-1.amazonaws.com", false, true);
        b(region2, "kms", "kms.ap-northeast-1.amazonaws.com", false, true);
        b(region2, "lambda", "lambda.ap-northeast-1.amazonaws.com", false, true);
        b(region2, "logs", "logs.ap-northeast-1.amazonaws.com", false, true);
        b(region2, "polly", "polly.ap-northeast-1.amazonaws.com", false, true);
        b(region2, "s3", "s3.ap-northeast-1.amazonaws.com", false, true);
        b(region2, ServiceAbbreviations.f21141l, "sdb.ap-northeast-1.amazonaws.com", false, true);
        b(region2, ServiceAbbreviations.f21142m, "sns.ap-northeast-1.amazonaws.com", false, true);
        b(region2, ServiceAbbreviations.f21143n, "sqs.ap-northeast-1.amazonaws.com", false, true);
        b(region2, ServiceAbbreviations.f21149t, "sts.ap-northeast-1.amazonaws.com", false, true);
        Region region3 = new Region("ap-northeast-2", "amazonaws.com");
        arrayList.add(region3);
        b(region3, ServiceAbbreviations.f21145p, "autoscaling.ap-northeast-2.amazonaws.com", false, true);
        b(region3, "cognito-identity", "cognito-identity.ap-northeast-2.amazonaws.com", false, true);
        b(region3, "cognito-idp", "cognito-idp.ap-northeast-2.amazonaws.com", false, true);
        b(region3, "cognito-sync", "cognito-sync.ap-northeast-2.amazonaws.com", false, true);
        b(region3, "data.iot", "data.iot.ap-northeast-2.amazonaws.com", false, true);
        b(region3, ServiceAbbreviations.f21134e, "dynamodb.ap-northeast-2.amazonaws.com", false, true);
        b(region3, ServiceAbbreviations.f21135f, "ec2.ap-northeast-2.amazonaws.com", false, true);
        b(region3, ServiceAbbreviations.f21151v, "elasticloadbalancing.ap-northeast-2.amazonaws.com", false, true);
        b(region3, "iot", "iot.ap-northeast-2.amazonaws.com", false, true);
        b(region3, "kinesis", "kinesis.ap-northeast-2.amazonaws.com", false, true);
        b(region3, "kms", "kms.ap-northeast-2.amazonaws.com", false, true);
        b(region3, "lambda", "lambda.ap-northeast-2.amazonaws.com", false, true);
        b(region3, "logs", "logs.ap-northeast-2.amazonaws.com", false, true);
        b(region3, "polly", "polly.ap-northeast-2.amazonaws.com", false, true);
        b(region3, "s3", "s3.ap-northeast-2.amazonaws.com", false, true);
        b(region3, ServiceAbbreviations.f21142m, "sns.ap-northeast-2.amazonaws.com", false, true);
        b(region3, ServiceAbbreviations.f21143n, "sqs.ap-northeast-2.amazonaws.com", false, true);
        b(region3, ServiceAbbreviations.f21149t, "sts.ap-northeast-2.amazonaws.com", false, true);
        Region region4 = new Region("ap-south-1", "amazonaws.com");
        arrayList.add(region4);
        b(region4, ServiceAbbreviations.f21145p, "autoscaling.ap-south-1.amazonaws.com", false, true);
        b(region4, "cognito-identity", "cognito-identity.ap-south-1.amazonaws.com", false, true);
        b(region4, "cognito-idp", "cognito-idp.ap-south-1.amazonaws.com", false, true);
        b(region4, "cognito-sync", "cognito-sync.ap-south-1.amazonaws.com", false, true);
        b(region4, ServiceAbbreviations.f21134e, "dynamodb.ap-south-1.amazonaws.com", false, true);
        b(region4, ServiceAbbreviations.f21135f, "ec2.ap-south-1.amazonaws.com", false, true);
        b(region4, ServiceAbbreviations.f21151v, "elasticloadbalancing.ap-south-1.amazonaws.com", false, true);
        b(region4, "kinesis", "kinesis.ap-south-1.amazonaws.com", false, true);
        b(region4, "kms", "kms.ap-south-1.amazonaws.com", false, true);
        b(region4, "lambda", "lambda.ap-south-1.amazonaws.com", false, true);
        b(region4, "logs", "logs.ap-south-1.amazonaws.com", false, true);
        b(region4, "polly", "polly.ap-south-1.amazonaws.com", false, true);
        b(region4, "s3", "s3.ap-south-1.amazonaws.com", false, true);
        b(region4, ServiceAbbreviations.f21142m, "sns.ap-south-1.amazonaws.com", false, true);
        b(region4, ServiceAbbreviations.f21143n, "sqs.ap-south-1.amazonaws.com", false, true);
        b(region4, ServiceAbbreviations.f21149t, "sts.ap-south-1.amazonaws.com", false, true);
        Region region5 = new Region("ap-southeast-1", "amazonaws.com");
        arrayList.add(region5);
        b(region5, ServiceAbbreviations.f21145p, "autoscaling.ap-southeast-1.amazonaws.com", false, true);
        b(region5, "cognito-identity", "cognito-identity.ap-southeast-1.amazonaws.com", false, true);
        b(region5, "cognito-idp", "cognito-idp.ap-southeast-1.amazonaws.com", false, true);
        b(region5, "cognito-sync", "cognito-sync.ap-southeast-1.amazonaws.com", false, true);
        b(region5, "data.iot", "data.iot.ap-southeast-1.amazonaws.com", false, true);
        b(region5, ServiceAbbreviations.f21134e, "dynamodb.ap-southeast-1.amazonaws.com", false, true);
        b(region5, ServiceAbbreviations.f21135f, "ec2.ap-southeast-1.amazonaws.com", false, true);
        b(region5, ServiceAbbreviations.f21151v, "elasticloadbalancing.ap-southeast-1.amazonaws.com", false, true);
        b(region5, "iot", "iot.ap-southeast-1.amazonaws.com", false, true);
        b(region5, "kinesis", "kinesis.ap-southeast-1.amazonaws.com", false, true);
        b(region5, "kms", "kms.ap-southeast-1.amazonaws.com", false, true);
        b(region5, "lambda", "lambda.ap-southeast-1.amazonaws.com", false, true);
        b(region5, "logs", "logs.ap-southeast-1.amazonaws.com", false, true);
        b(region5, "polly", "polly.ap-southeast-1.amazonaws.com", false, true);
        b(region5, "s3", "s3.ap-southeast-1.amazonaws.com", false, true);
        b(region5, ServiceAbbreviations.f21141l, "sdb.ap-southeast-1.amazonaws.com", false, true);
        b(region5, ServiceAbbreviations.f21142m, "sns.ap-southeast-1.amazonaws.com", false, true);
        b(region5, ServiceAbbreviations.f21143n, "sqs.ap-southeast-1.amazonaws.com", false, true);
        b(region5, ServiceAbbreviations.f21149t, "sts.ap-southeast-1.amazonaws.com", false, true);
        Region region6 = new Region("ap-southeast-2", "amazonaws.com");
        arrayList.add(region6);
        b(region6, ServiceAbbreviations.f21145p, "autoscaling.ap-southeast-2.amazonaws.com", false, true);
        b(region6, "cognito-identity", "cognito-identity.ap-southeast-2.amazonaws.com", false, true);
        b(region6, "cognito-idp", "cognito-idp.ap-southeast-2.amazonaws.com", false, true);
        b(region6, "cognito-sync", "cognito-sync.ap-southeast-2.amazonaws.com", false, true);
        b(region6, "data.iot", "data.iot.ap-southeast-2.amazonaws.com", false, true);
        b(region6, ServiceAbbreviations.f21134e, "dynamodb.ap-southeast-2.amazonaws.com", false, true);
        b(region6, ServiceAbbreviations.f21135f, "ec2.ap-southeast-2.amazonaws.com", false, true);
        b(region6, ServiceAbbreviations.f21151v, "elasticloadbalancing.ap-southeast-2.amazonaws.com", false, true);
        b(region6, "iot", "iot.ap-southeast-2.amazonaws.com", false, true);
        b(region6, "kinesis", "kinesis.ap-southeast-2.amazonaws.com", false, true);
        b(region6, "kms", "kms.ap-southeast-2.amazonaws.com", false, true);
        b(region6, "lambda", "lambda.ap-southeast-2.amazonaws.com", false, true);
        b(region6, "logs", "logs.ap-southeast-2.amazonaws.com", false, true);
        b(region6, "polly", "polly.ap-southeast-2.amazonaws.com", false, true);
        b(region6, "s3", "s3.ap-southeast-2.amazonaws.com", false, true);
        b(region6, ServiceAbbreviations.f21141l, "sdb.ap-southeast-2.amazonaws.com", false, true);
        b(region6, ServiceAbbreviations.f21142m, "sns.ap-southeast-2.amazonaws.com", false, true);
        b(region6, ServiceAbbreviations.f21143n, "sqs.ap-southeast-2.amazonaws.com", false, true);
        b(region6, ServiceAbbreviations.f21149t, "sts.ap-southeast-2.amazonaws.com", false, true);
        Region region7 = new Region("ca-central-1", "amazonaws.com");
        arrayList.add(region7);
        b(region7, ServiceAbbreviations.f21145p, "autoscaling.ca-central-1.amazonaws.com", false, true);
        b(region7, ServiceAbbreviations.f21134e, "dynamodb.ca-central-1.amazonaws.com", false, true);
        b(region7, ServiceAbbreviations.f21135f, "ec2.ca-central-1.amazonaws.com", false, true);
        b(region7, ServiceAbbreviations.f21151v, "elasticloadbalancing.ca-central-1.amazonaws.com", false, true);
        b(region7, "kinesis", "kinesis.ca-central-1.amazonaws.com", false, true);
        b(region7, "kms", "kms.ca-central-1.amazonaws.com", false, true);
        b(region7, "lambda", "lambda.ca-central-1.amazonaws.com", false, true);
        b(region7, "logs", "logs.ca-central-1.amazonaws.com", false, true);
        b(region7, "polly", "polly.ca-central-1.amazonaws.com", false, true);
        b(region7, "s3", "s3.ca-central-1.amazonaws.com", false, true);
        b(region7, ServiceAbbreviations.f21142m, "sns.ca-central-1.amazonaws.com", false, true);
        b(region7, ServiceAbbreviations.f21143n, "sqs.ca-central-1.amazonaws.com", false, true);
        b(region7, ServiceAbbreviations.f21149t, "sts.ca-central-1.amazonaws.com", false, true);
        Region region8 = new Region("eu-central-1", "amazonaws.com");
        arrayList.add(region8);
        b(region8, ServiceAbbreviations.f21145p, "autoscaling.eu-central-1.amazonaws.com", false, true);
        b(region8, "cognito-identity", "cognito-identity.eu-central-1.amazonaws.com", false, true);
        b(region8, "cognito-idp", "cognito-idp.eu-central-1.amazonaws.com", false, true);
        b(region8, "cognito-sync", "cognito-sync.eu-central-1.amazonaws.com", false, true);
        b(region8, "data.iot", "data.iot.eu-central-1.amazonaws.com", false, true);
        b(region8, ServiceAbbreviations.f21134e, "dynamodb.eu-central-1.amazonaws.com", false, true);
        b(region8, ServiceAbbreviations.f21135f, "ec2.eu-central-1.amazonaws.com", false, true);
        b(region8, ServiceAbbreviations.f21151v, "elasticloadbalancing.eu-central-1.amazonaws.com", false, true);
        b(region8, "firehose", "firehose.eu-central-1.amazonaws.com", false, true);
        b(region8, "iot", "iot.eu-central-1.amazonaws.com", false, true);
        b(region8, "kinesis", "kinesis.eu-central-1.amazonaws.com", false, true);
        b(region8, "kms", "kms.eu-central-1.amazonaws.com", false, true);
        b(region8, "lambda", "lambda.eu-central-1.amazonaws.com", false, true);
        b(region8, "logs", "logs.eu-central-1.amazonaws.com", false, true);
        b(region8, "polly", "polly.eu-central-1.amazonaws.com", false, true);
        b(region8, "s3", "s3.eu-central-1.amazonaws.com", false, true);
        b(region8, ServiceAbbreviations.f21142m, "sns.eu-central-1.amazonaws.com", false, true);
        b(region8, ServiceAbbreviations.f21143n, "sqs.eu-central-1.amazonaws.com", false, true);
        b(region8, ServiceAbbreviations.f21149t, "sts.eu-central-1.amazonaws.com", false, true);
        Region region9 = new Region("eu-central-2", "amazonaws.com");
        arrayList.add(region9);
        b(region9, ServiceAbbreviations.f21145p, "autoscaling.eu-central-2.amazonaws.com", false, true);
        b(region9, "cognito-identity", "cognito-identity.eu-central-2.amazonaws.com", false, true);
        b(region9, "cognito-idp", "cognito-idp.eu-central-2.amazonaws.com", false, true);
        b(region9, "cognito-sync", "cognito-sync.eu-central-2.amazonaws.com", false, true);
        b(region9, "data.iot", "data.iot.eu-central-2.amazonaws.com", false, true);
        b(region9, ServiceAbbreviations.f21134e, "dynamodb.eu-central-2.amazonaws.com", false, true);
        b(region9, ServiceAbbreviations.f21135f, "ec2.eu-central-2.amazonaws.com", false, true);
        b(region9, ServiceAbbreviations.f21151v, "elasticloadbalancing.eu-central-2.amazonaws.com", false, true);
        b(region9, "firehose", "firehose.eu-central-2.amazonaws.com", false, true);
        b(region9, "iot", "iot.eu-central-2.amazonaws.com", false, true);
        b(region9, "kinesis", "kinesis.eu-central-2.amazonaws.com", false, true);
        b(region9, "kms", "kms.eu-central-2.amazonaws.com", false, true);
        b(region9, "lambda", "lambda.eu-central-2.amazonaws.com", false, true);
        b(region9, "logs", "logs.eu-central-2.amazonaws.com", false, true);
        b(region9, "polly", "polly.eu-central-2.amazonaws.com", false, true);
        b(region9, "s3", "s3.eu-central-2.amazonaws.com", false, true);
        b(region9, ServiceAbbreviations.f21141l, "sdb.eu-central-2.amazonaws.com", false, true);
        b(region9, ServiceAbbreviations.f21142m, "sns.eu-central-2.amazonaws.com", false, true);
        b(region9, ServiceAbbreviations.f21143n, "sqs.eu-central-2.amazonaws.com", false, true);
        b(region9, ServiceAbbreviations.f21149t, "sts.eu-central-2.amazonaws.com", false, true);
        Region region10 = new Region("eu-south-1", "amazonaws.com");
        arrayList.add(region10);
        b(region10, ServiceAbbreviations.f21145p, "autoscaling.eu-south-1.amazonaws.com", false, true);
        b(region10, ServiceAbbreviations.f21134e, "dynamodb.eu-south-1.amazonaws.com", false, true);
        b(region10, ServiceAbbreviations.f21135f, "ec2.eu-south-1.amazonaws.com", false, true);
        b(region10, ServiceAbbreviations.f21151v, "elasticloadbalancing.eu-south-1.amazonaws.com", false, true);
        b(region10, "lambda", "lambda.eu-south-1.amazonaws.com", false, true);
        b(region10, "logs", "logs.eu-south-1.amazonaws.com", false, true);
        b(region10, "s3", "s3.eu-south-1.amazonaws.com", false, true);
        b(region10, ServiceAbbreviations.f21142m, "sns.eu-south-1.amazonaws.com", false, true);
        b(region10, ServiceAbbreviations.f21143n, "sqs.eu-south-1.amazonaws.com", false, true);
        b(region10, ServiceAbbreviations.f21149t, "sts.eu-south-1.amazonaws.com", false, true);
        Region region11 = new Region("eu-south-2", "amazonaws.com");
        arrayList.add(region11);
        b(region11, ServiceAbbreviations.f21145p, "autoscaling.eu-south-2.amazonaws.com", false, true);
        b(region11, "cognito-identity", "cognito-identity.eu-south-2.amazonaws.com", false, true);
        b(region11, "cognito-idp", "cognito-idp.eu-south-2.amazonaws.com", false, true);
        b(region11, "cognito-sync", "cognito-sync.eu-south-2.amazonaws.com", false, true);
        b(region11, "data.iot", "data.iot.eu-south-2.amazonaws.com", false, true);
        b(region11, ServiceAbbreviations.f21134e, "dynamodb.eu-south-2.amazonaws.com", false, true);
        b(region11, ServiceAbbreviations.f21135f, "ec2.eu-south-2.amazonaws.com", false, true);
        b(region11, ServiceAbbreviations.f21151v, "elasticloadbalancing.eu-south-2.amazonaws.com", false, true);
        b(region11, "firehose", "firehose.eu-south-2.amazonaws.com", false, true);
        b(region11, "iot", "iot.eu-south-2.amazonaws.com", false, true);
        b(region11, "kinesis", "kinesis.eu-south-2.amazonaws.com", false, true);
        b(region11, "kms", "kms.eu-south-2.amazonaws.com", false, true);
        b(region11, "lambda", "lambda.eu-south-2.amazonaws.com", false, true);
        b(region11, "logs", "logs.eu-south-2.amazonaws.com", false, true);
        b(region11, "polly", "polly.eu-south-2.amazonaws.com", false, true);
        b(region11, "s3", "s3.eu-south-2.amazonaws.com", false, true);
        b(region11, ServiceAbbreviations.f21141l, "sdb.eu-south-2.amazonaws.com", false, true);
        b(region11, ServiceAbbreviations.f21142m, "sns.eu-south-2.amazonaws.com", false, true);
        b(region11, ServiceAbbreviations.f21143n, "sqs.eu-south-2.amazonaws.com", false, true);
        b(region11, ServiceAbbreviations.f21149t, "sts.eu-south-2.amazonaws.com", false, true);
        Region region12 = new Region("eu-west-1", "amazonaws.com");
        arrayList.add(region12);
        b(region12, ServiceAbbreviations.f21145p, "autoscaling.eu-west-1.amazonaws.com", false, true);
        b(region12, "cognito-identity", "cognito-identity.eu-west-1.amazonaws.com", false, true);
        b(region12, "cognito-idp", "cognito-idp.eu-west-1.amazonaws.com", false, true);
        b(region12, "cognito-sync", "cognito-sync.eu-west-1.amazonaws.com", false, true);
        b(region12, "data.iot", "data.iot.eu-west-1.amazonaws.com", false, true);
        b(region12, ServiceAbbreviations.f21134e, "dynamodb.eu-west-1.amazonaws.com", false, true);
        b(region12, ServiceAbbreviations.f21135f, "ec2.eu-west-1.amazonaws.com", false, true);
        b(region12, ServiceAbbreviations.f21151v, "elasticloadbalancing.eu-west-1.amazonaws.com", false, true);
        b(region12, "email", "email.eu-west-1.amazonaws.com", false, true);
        b(region12, "firehose", "firehose.eu-west-1.amazonaws.com", false, true);
        b(region12, "iot", "iot.eu-west-1.amazonaws.com", false, true);
        b(region12, "kinesis", "kinesis.eu-west-1.amazonaws.com", false, true);
        b(region12, "kms", "kms.eu-west-1.amazonaws.com", false, true);
        b(region12, "lambda", "lambda.eu-west-1.amazonaws.com", false, true);
        b(region12, "logs", "logs.eu-west-1.amazonaws.com", false, true);
        b(region12, "machinelearning", "machinelearning.eu-west-1.amazonaws.com", false, true);
        b(region12, "polly", "polly.eu-west-1.amazonaws.com", false, true);
        b(region12, "rekognition", "rekognition.eu-west-1.amazonaws.com", false, true);
        b(region12, "s3", "s3.eu-west-1.amazonaws.com", false, true);
        b(region12, ServiceAbbreviations.f21141l, "sdb.eu-west-1.amazonaws.com", false, true);
        b(region12, ServiceAbbreviations.f21142m, "sns.eu-west-1.amazonaws.com", false, true);
        b(region12, ServiceAbbreviations.f21143n, "sqs.eu-west-1.amazonaws.com", false, true);
        b(region12, ServiceAbbreviations.f21149t, "sts.eu-west-1.amazonaws.com", false, true);
        Region region13 = new Region("eu-west-2", "amazonaws.com");
        arrayList.add(region13);
        b(region13, ServiceAbbreviations.f21145p, "autoscaling.eu-west-2.amazonaws.com", false, true);
        b(region13, "cognito-identity", "cognito-identity.eu-west-2.amazonaws.com", false, true);
        b(region13, "cognito-idp", "cognito-idp.eu-west-2.amazonaws.com", false, true);
        b(region13, "cognito-sync", "cognito-sync.eu-west-2.amazonaws.com", false, true);
        b(region13, ServiceAbbreviations.f21134e, "dynamodb.eu-west-2.amazonaws.com", false, true);
        b(region13, ServiceAbbreviations.f21135f, "ec2.eu-west-2.amazonaws.com", false, true);
        b(region13, ServiceAbbreviations.f21151v, "elasticloadbalancing.eu-west-2.amazonaws.com", false, true);
        b(region13, "iot", "iot.eu-west-2.amazonaws.com", false, true);
        b(region13, "kinesis", "kinesis.eu-west-2.amazonaws.com", false, true);
        b(region13, "kms", "kms.eu-west-2.amazonaws.com", false, true);
        b(region13, "lambda", "lambda.eu-west-2.amazonaws.com", false, true);
        b(region13, "logs", "logs.eu-west-2.amazonaws.com", false, true);
        b(region13, "polly", "polly.eu-west-2.amazonaws.com", false, true);
        b(region13, "s3", "s3.eu-west-2.amazonaws.com", false, true);
        b(region13, ServiceAbbreviations.f21142m, "sns.eu-west-2.amazonaws.com", false, true);
        b(region13, ServiceAbbreviations.f21143n, "sqs.eu-west-2.amazonaws.com", false, true);
        b(region13, ServiceAbbreviations.f21149t, "sts.eu-west-2.amazonaws.com", false, true);
        Region region14 = new Region("eu-west-3", "amazonaws.com");
        arrayList.add(region14);
        b(region14, ServiceAbbreviations.f21145p, "autoscaling.eu-west-3.amazonaws.com", false, true);
        b(region14, ServiceAbbreviations.f21134e, "dynamodb.eu-west-3.amazonaws.com", false, true);
        b(region14, ServiceAbbreviations.f21135f, "ec2.eu-west-3.amazonaws.com", false, true);
        b(region14, ServiceAbbreviations.f21151v, "elasticloadbalancing.eu-west-3.amazonaws.com", false, true);
        b(region14, "kinesis", "kinesis.eu-west-3.amazonaws.com", false, true);
        b(region14, "kms", "kms.eu-west-3.amazonaws.com", false, true);
        b(region14, "lambda", "lambda.eu-west-3.amazonaws.com", false, true);
        b(region14, "logs", "logs.eu-west-3.amazonaws.com", false, true);
        b(region14, "polly", "polly.eu-west-3.amazonaws.com", false, true);
        b(region14, "s3", "s3.eu-west-3.amazonaws.com", false, true);
        b(region14, ServiceAbbreviations.f21142m, "sns.eu-west-3.amazonaws.com", false, true);
        b(region14, ServiceAbbreviations.f21143n, "sqs.eu-west-3.amazonaws.com", false, true);
        b(region14, ServiceAbbreviations.f21149t, "sts.eu-west-3.amazonaws.com", false, true);
        Region region15 = new Region("sa-east-1", "amazonaws.com");
        arrayList.add(region15);
        b(region15, ServiceAbbreviations.f21145p, "autoscaling.sa-east-1.amazonaws.com", false, true);
        b(region15, ServiceAbbreviations.f21134e, "dynamodb.sa-east-1.amazonaws.com", false, true);
        b(region15, ServiceAbbreviations.f21135f, "ec2.sa-east-1.amazonaws.com", false, true);
        b(region15, ServiceAbbreviations.f21151v, "elasticloadbalancing.sa-east-1.amazonaws.com", false, true);
        b(region15, "kinesis", "kinesis.sa-east-1.amazonaws.com", false, true);
        b(region15, "kms", "kms.sa-east-1.amazonaws.com", false, true);
        b(region15, "lambda", "lambda.sa-east-1.amazonaws.com", false, true);
        b(region15, "logs", "logs.sa-east-1.amazonaws.com", false, true);
        b(region15, "polly", "polly.sa-east-1.amazonaws.com", false, true);
        b(region15, "s3", "s3.sa-east-1.amazonaws.com", false, true);
        b(region15, ServiceAbbreviations.f21141l, "sdb.sa-east-1.amazonaws.com", false, true);
        b(region15, ServiceAbbreviations.f21142m, "sns.sa-east-1.amazonaws.com", false, true);
        b(region15, ServiceAbbreviations.f21143n, "sqs.sa-east-1.amazonaws.com", false, true);
        b(region15, ServiceAbbreviations.f21149t, "sts.sa-east-1.amazonaws.com", false, true);
        Region region16 = new Region("us-east-1", "amazonaws.com");
        arrayList.add(region16);
        b(region16, ServiceAbbreviations.f21145p, "autoscaling.us-east-1.amazonaws.com", false, true);
        b(region16, "cognito-identity", "cognito-identity.us-east-1.amazonaws.com", false, true);
        b(region16, "cognito-idp", "cognito-idp.us-east-1.amazonaws.com", false, true);
        b(region16, "cognito-sync", "cognito-sync.us-east-1.amazonaws.com", false, true);
        b(region16, "data.iot", "data.iot.us-east-1.amazonaws.com", false, true);
        b(region16, ServiceAbbreviations.f21134e, "dynamodb.us-east-1.amazonaws.com", false, true);
        b(region16, ServiceAbbreviations.f21135f, "ec2.us-east-1.amazonaws.com", false, true);
        b(region16, ServiceAbbreviations.f21151v, "elasticloadbalancing.us-east-1.amazonaws.com", false, true);
        b(region16, "email", "email.us-east-1.amazonaws.com", false, true);
        b(region16, "firehose", "firehose.us-east-1.amazonaws.com", false, true);
        b(region16, "iot", "iot.us-east-1.amazonaws.com", false, true);
        b(region16, "kinesis", "kinesis.us-east-1.amazonaws.com", false, true);
        b(region16, "kms", "kms.us-east-1.amazonaws.com", false, true);
        b(region16, "lambda", "lambda.us-east-1.amazonaws.com", false, true);
        b(region16, "logs", "logs.us-east-1.amazonaws.com", false, true);
        b(region16, "machinelearning", "machinelearning.us-east-1.amazonaws.com", false, true);
        b(region16, "mobileanalytics", "mobileanalytics.us-east-1.amazonaws.com", false, true);
        b(region16, "pinpoint", "pinpoint.us-east-1.amazonaws.com", false, true);
        b(region16, "polly", "polly.us-east-1.amazonaws.com", false, true);
        b(region16, "rekognition", "rekognition.us-east-1.amazonaws.com", false, true);
        b(region16, "s3", Constants.f23318b, false, true);
        b(region16, ServiceAbbreviations.f21141l, "sdb.amazonaws.com", false, true);
        b(region16, ServiceAbbreviations.f21142m, "sns.us-east-1.amazonaws.com", false, true);
        b(region16, ServiceAbbreviations.f21143n, "sqs.us-east-1.amazonaws.com", false, true);
        b(region16, ServiceAbbreviations.f21149t, "sts.us-east-1.amazonaws.com", false, true);
        Region region17 = new Region("us-east-2", "amazonaws.com");
        arrayList.add(region17);
        b(region17, ServiceAbbreviations.f21145p, "autoscaling.us-east-2.amazonaws.com", false, true);
        b(region17, "cognito-identity", "cognito-identity.us-east-2.amazonaws.com", false, true);
        b(region17, "cognito-idp", "cognito-idp.us-east-2.amazonaws.com", false, true);
        b(region17, "cognito-sync", "cognito-sync.us-east-2.amazonaws.com", false, true);
        b(region17, ServiceAbbreviations.f21134e, "dynamodb.us-east-2.amazonaws.com", false, true);
        b(region17, ServiceAbbreviations.f21135f, "ec2.us-east-2.amazonaws.com", false, true);
        b(region17, ServiceAbbreviations.f21151v, "elasticloadbalancing.us-east-2.amazonaws.com", false, true);
        b(region17, "firehose", "firehose.us-east-2.amazonaws.com", false, true);
        b(region17, "iot", "iot.us-east-2.amazonaws.com", false, true);
        b(region17, "kinesis", "kinesis.us-east-2.amazonaws.com", false, true);
        b(region17, "kms", "kms.us-east-2.amazonaws.com", false, true);
        b(region17, "lambda", "lambda.us-east-2.amazonaws.com", false, true);
        b(region17, "logs", "logs.us-east-2.amazonaws.com", false, true);
        b(region17, "polly", "polly.us-east-2.amazonaws.com", false, true);
        b(region17, "s3", "s3.us-east-2.amazonaws.com", false, true);
        b(region17, ServiceAbbreviations.f21142m, "sns.us-east-2.amazonaws.com", false, true);
        b(region17, ServiceAbbreviations.f21143n, "sqs.us-east-2.amazonaws.com", false, true);
        b(region17, ServiceAbbreviations.f21149t, "sts.us-east-2.amazonaws.com", false, true);
        Region region18 = new Region("us-west-1", "amazonaws.com");
        arrayList.add(region18);
        b(region18, ServiceAbbreviations.f21145p, "autoscaling.us-west-1.amazonaws.com", false, true);
        b(region18, ServiceAbbreviations.f21134e, "dynamodb.us-west-1.amazonaws.com", false, true);
        b(region18, ServiceAbbreviations.f21135f, "ec2.us-west-1.amazonaws.com", false, true);
        b(region18, ServiceAbbreviations.f21151v, "elasticloadbalancing.us-west-1.amazonaws.com", false, true);
        b(region18, "kinesis", "kinesis.us-west-1.amazonaws.com", false, true);
        b(region18, "kms", "kms.us-west-1.amazonaws.com", false, true);
        b(region18, "lambda", "lambda.us-west-1.amazonaws.com", false, true);
        b(region18, "logs", "logs.us-west-1.amazonaws.com", false, true);
        b(region18, "polly", "polly.us-west-1.amazonaws.com", false, true);
        b(region18, "s3", "s3.us-west-1.amazonaws.com", false, true);
        b(region18, ServiceAbbreviations.f21141l, "sdb.us-west-1.amazonaws.com", false, true);
        b(region18, ServiceAbbreviations.f21142m, "sns.us-west-1.amazonaws.com", false, true);
        b(region18, ServiceAbbreviations.f21143n, "sqs.us-west-1.amazonaws.com", false, true);
        b(region18, ServiceAbbreviations.f21149t, "sts.us-west-1.amazonaws.com", false, true);
        Region region19 = new Region("us-west-2", "amazonaws.com");
        arrayList.add(region19);
        b(region19, ServiceAbbreviations.f21145p, "autoscaling.us-west-2.amazonaws.com", false, true);
        b(region19, "cognito-identity", "cognito-identity.us-west-2.amazonaws.com", false, true);
        b(region19, "cognito-idp", "cognito-idp.us-west-2.amazonaws.com", false, true);
        b(region19, "cognito-sync", "cognito-sync.us-west-2.amazonaws.com", false, true);
        b(region19, "data.iot", "data.iot.us-west-2.amazonaws.com", false, true);
        b(region19, ServiceAbbreviations.f21134e, "dynamodb.us-west-2.amazonaws.com", false, true);
        b(region19, ServiceAbbreviations.f21135f, "ec2.us-west-2.amazonaws.com", false, true);
        b(region19, ServiceAbbreviations.f21151v, "elasticloadbalancing.us-west-2.amazonaws.com", false, true);
        b(region19, "email", "email.us-west-2.amazonaws.com", false, true);
        b(region19, "firehose", "firehose.us-west-2.amazonaws.com", false, true);
        b(region19, "iot", "iot.us-west-2.amazonaws.com", false, true);
        b(region19, "kinesis", "kinesis.us-west-2.amazonaws.com", false, true);
        b(region19, "kms", "kms.us-west-2.amazonaws.com", false, true);
        b(region19, "lambda", "lambda.us-west-2.amazonaws.com", false, true);
        b(region19, "logs", "logs.us-west-2.amazonaws.com", false, true);
        b(region19, "polly", "polly.us-west-2.amazonaws.com", false, true);
        b(region19, "rekognition", "rekognition.us-west-2.amazonaws.com", false, true);
        b(region19, "s3", "s3.us-west-2.amazonaws.com", false, true);
        b(region19, ServiceAbbreviations.f21141l, "sdb.us-west-2.amazonaws.com", false, true);
        b(region19, ServiceAbbreviations.f21142m, "sns.us-west-2.amazonaws.com", false, true);
        b(region19, ServiceAbbreviations.f21143n, "sqs.us-west-2.amazonaws.com", false, true);
        b(region19, ServiceAbbreviations.f21149t, "sts.us-west-2.amazonaws.com", false, true);
        Region region20 = new Region("cn-north-1", "amazonaws.com.cn");
        arrayList.add(region20);
        b(region20, ServiceAbbreviations.f21145p, "autoscaling.cn-north-1.amazonaws.com.cn", false, true);
        b(region20, "cognito-identity", "cognito-identity.cn-north-1.amazonaws.com.cn", false, true);
        b(region20, ServiceAbbreviations.f21134e, "dynamodb.cn-north-1.amazonaws.com.cn", false, true);
        b(region20, ServiceAbbreviations.f21135f, "ec2.cn-north-1.amazonaws.com.cn", false, true);
        b(region20, ServiceAbbreviations.f21151v, "elasticloadbalancing.cn-north-1.amazonaws.com.cn", false, true);
        b(region20, "iot", "iot.cn-north-1.amazonaws.com.cn", false, true);
        b(region20, "kinesis", "kinesis.cn-north-1.amazonaws.com.cn", false, true);
        b(region20, "lambda", "lambda.cn-north-1.amazonaws.com.cn", false, true);
        b(region20, "logs", "logs.cn-north-1.amazonaws.com.cn", false, true);
        b(region20, "s3", "s3.cn-north-1.amazonaws.com.cn", false, true);
        b(region20, ServiceAbbreviations.f21142m, "sns.cn-north-1.amazonaws.com.cn", false, true);
        b(region20, ServiceAbbreviations.f21143n, "sqs.cn-north-1.amazonaws.com.cn", false, true);
        b(region20, ServiceAbbreviations.f21149t, "sts.cn-north-1.amazonaws.com.cn", false, true);
        Region region21 = new Region("cn-northwest-1", "amazonaws.com.cn");
        arrayList.add(region21);
        b(region21, ServiceAbbreviations.f21145p, "autoscaling.cn-northwest-1.amazonaws.com.cn", false, true);
        b(region21, ServiceAbbreviations.f21134e, "dynamodb.cn-northwest-1.amazonaws.com.cn", false, true);
        b(region21, ServiceAbbreviations.f21135f, "ec2.cn-northwest-1.amazonaws.com.cn", false, true);
        b(region21, ServiceAbbreviations.f21151v, "elasticloadbalancing.cn-northwest-1.amazonaws.com.cn", false, true);
        b(region21, "kinesis", "kinesis.cn-northwest-1.amazonaws.com.cn", false, true);
        b(region21, "logs", "logs.cn-northwest-1.amazonaws.com.cn", false, true);
        b(region21, "s3", "s3.cn-northwest-1.amazonaws.com.cn", false, true);
        b(region21, ServiceAbbreviations.f21142m, "sns.cn-northwest-1.amazonaws.com.cn", false, true);
        b(region21, ServiceAbbreviations.f21143n, "sqs.cn-northwest-1.amazonaws.com.cn", false, true);
        b(region21, ServiceAbbreviations.f21149t, "sts.cn-northwest-1.amazonaws.com.cn", false, true);
        Region region22 = new Region("us-gov-west-1", "amazonaws.com");
        arrayList.add(region22);
        b(region22, ServiceAbbreviations.f21145p, "autoscaling.us-gov-west-1.amazonaws.com", false, true);
        b(region22, ServiceAbbreviations.f21134e, "dynamodb.us-gov-west-1.amazonaws.com", false, true);
        b(region22, ServiceAbbreviations.f21135f, "ec2.us-gov-west-1.amazonaws.com", false, true);
        b(region22, ServiceAbbreviations.f21151v, "elasticloadbalancing.us-gov-west-1.amazonaws.com", false, true);
        b(region22, "kinesis", "kinesis.us-gov-west-1.amazonaws.com", false, true);
        b(region22, "kms", "kms.us-gov-west-1.amazonaws.com", false, true);
        b(region22, "lambda", "lambda.us-gov-west-1.amazonaws.com", false, true);
        b(region22, "logs", "logs.us-gov-west-1.amazonaws.com", false, true);
        b(region22, "rekognition", "rekognition.us-gov-west-1.amazonaws.com", false, true);
        b(region22, "s3", "s3.us-gov-west-1.amazonaws.com", false, true);
        b(region22, ServiceAbbreviations.f21142m, "sns.us-gov-west-1.amazonaws.com", false, true);
        b(region22, ServiceAbbreviations.f21143n, "sqs.us-gov-west-1.amazonaws.com", false, true);
        b(region22, ServiceAbbreviations.f21149t, "sts.us-gov-west-1.amazonaws.com", false, true);
        Region region23 = new Region("us-gov-east-1", "amazonaws.com");
        arrayList.add(region23);
        b(region23, ServiceAbbreviations.f21145p, "autoscaling.us-gov-east-1.amazonaws.com", false, true);
        b(region23, ServiceAbbreviations.f21134e, "dynamodb.us-gov-east-1.amazonaws.com", false, true);
        b(region23, ServiceAbbreviations.f21135f, "ec2.us-gov-east-1.amazonaws.com", false, true);
        b(region23, ServiceAbbreviations.f21151v, "elasticloadbalancing.us-gov-east-1.amazonaws.com", false, true);
        b(region23, "kinesis", "kinesis.us-gov-east-1.amazonaws.com", false, true);
        b(region23, "kms", "kms.us-gov-east-1.amazonaws.com", false, true);
        b(region23, "lambda", "lambda.us-gov-east-1.amazonaws.com", false, true);
        b(region23, "logs", "logs.us-gov-east-1.amazonaws.com", false, true);
        b(region23, "rekognition", "rekognition.us-gov-east-1.amazonaws.com", false, true);
        b(region23, "s3", "s3.us-gov-east-1.amazonaws.com", false, true);
        b(region23, ServiceAbbreviations.f21142m, "sns.us-gov-east-1.amazonaws.com", false, true);
        b(region23, ServiceAbbreviations.f21143n, "sqs.us-gov-east-1.amazonaws.com", false, true);
        b(region23, ServiceAbbreviations.f21149t, "sts.us-gov-east-1.amazonaws.com", false, true);
        Region region24 = new Region("eu-north-1", "amazonaws.com");
        arrayList.add(region24);
        b(region24, ServiceAbbreviations.f21145p, "autoscaling.eu-north-1.amazonaws.com", false, true);
        b(region24, ServiceAbbreviations.f21134e, "dynamodb.eu-north-1.amazonaws.com", false, true);
        b(region24, ServiceAbbreviations.f21135f, "ec2.eu-north-1.amazonaws.com", false, true);
        b(region24, ServiceAbbreviations.f21151v, "elasticloadbalancing.eu-north-1.amazonaws.com", false, true);
        b(region24, "firehose", "firehose.eu-north-1.amazonaws.com", false, true);
        b(region24, "iot", "iot.eu-north-1.amazonaws.com", false, true);
        b(region24, "kinesis", "kinesis.eu-north-1.amazonaws.com", false, true);
        b(region24, "kms", "kms.eu-north-1.amazonaws.com", false, true);
        b(region24, "lambda", "lambda.eu-north-1.amazonaws.com", false, true);
        b(region24, "logs", "logs.eu-north-1.amazonaws.com", false, true);
        b(region24, "s3", "s3.eu-north-1.amazonaws.com", false, true);
        b(region24, ServiceAbbreviations.f21142m, "sns.eu-north-1.amazonaws.com", false, true);
        b(region24, ServiceAbbreviations.f21143n, "sqs.eu-north-1.amazonaws.com", false, true);
        b(region24, ServiceAbbreviations.f21149t, "sts.eu-north-1.amazonaws.com", false, true);
        Region region25 = new Region("ap-east-1", "amazonaws.com");
        arrayList.add(region25);
        b(region25, ServiceAbbreviations.f21145p, "autoscaling.ap-east-1.amazonaws.com", false, true);
        b(region25, ServiceAbbreviations.f21134e, "dynamodb.ap-east-1.amazonaws.com", false, true);
        b(region25, ServiceAbbreviations.f21135f, "ec2.ap-east-1.amazonaws.com", false, true);
        b(region25, ServiceAbbreviations.f21151v, "elasticloadbalancing.ap-east-1.amazonaws.com", false, true);
        b(region25, "firehose", "firehose.ap-east-1.amazonaws.com", false, true);
        b(region25, "kinesis", "kinesis.ap-east-1.amazonaws.com", false, true);
        b(region25, "kms", "kms.ap-east-1.amazonaws.com", false, true);
        b(region25, "lambda", "lambda.ap-east-1.amazonaws.com", false, true);
        b(region25, "logs", "logs.ap-east-1.amazonaws.com", false, true);
        b(region25, "polly", "polly.ap-east-1.amazonaws.com", false, true);
        b(region25, "s3", "s3.ap-east-1.amazonaws.com", false, true);
        b(region25, ServiceAbbreviations.f21142m, "sns.ap-east-1.amazonaws.com", false, true);
        b(region25, ServiceAbbreviations.f21143n, "sqs.ap-east-1.amazonaws.com", false, true);
        b(region25, ServiceAbbreviations.f21149t, "sts.ap-east-1.amazonaws.com", false, true);
        Region region26 = new Region("me-south-1", "amazonaws.com");
        arrayList.add(region26);
        b(region26, ServiceAbbreviations.f21145p, "autoscaling.me-south-1.amazonaws.com", false, true);
        b(region26, "cognito-identity", "cognito-identity.me-south-1.amazonaws.com", false, true);
        b(region26, "cognito-idp", "cognito-idp.me-south-1.amazonaws.com", false, true);
        b(region26, "cognito-sync", "cognito-sync.me-south-1.amazonaws.com", false, true);
        b(region26, "data.iot", "data.iot.me-south-1.amazonaws.com", false, true);
        b(region26, ServiceAbbreviations.f21134e, "dynamodb.me-south-1.amazonaws.com", false, true);
        b(region26, ServiceAbbreviations.f21135f, "ec2.me-south-1.amazonaws.com", false, true);
        b(region26, ServiceAbbreviations.f21151v, "elasticloadbalancing.me-south-1.amazonaws.com", false, true);
        b(region26, "firehose", "firehose.me-south-1.amazonaws.com", false, true);
        b(region26, "iot", "iot.me-south-1.amazonaws.com", false, true);
        b(region26, "kinesis", "kinesis.me-south-1.amazonaws.com", false, true);
        b(region26, "kms", "kms.me-south-1.amazonaws.com", false, true);
        b(region26, "lambda", "lambda.me-south-1.amazonaws.com", false, true);
        b(region26, "logs", "logs.me-south-1.amazonaws.com", false, true);
        b(region26, "polly", "polly.me-south-1.amazonaws.com", false, true);
        b(region26, "s3", "s3.me-south-1.amazonaws.com", false, true);
        b(region26, ServiceAbbreviations.f21141l, "sdb.me-south-1.amazonaws.com", false, true);
        b(region26, ServiceAbbreviations.f21142m, "sns.me-south-1.amazonaws.com", false, true);
        b(region26, ServiceAbbreviations.f21143n, "sqs.me-south-1.amazonaws.com", false, true);
        b(region26, ServiceAbbreviations.f21149t, "sts.me-south-1.amazonaws.com", false, true);
        Region region27 = new Region("ap-southeast-3", "amazonaws.com");
        arrayList.add(region27);
        b(region27, ServiceAbbreviations.f21145p, "autoscaling.ap-southeast-3.amazonaws.com", false, true);
        b(region27, "cognito-identity", "cognito-identity.ap-southeast-3.amazonaws.com", false, true);
        b(region27, "cognito-idp", "cognito-idp.ap-southeast-3.amazonaws.com", false, true);
        b(region27, "cognito-sync", "cognito-sync.ap-southeast-3.amazonaws.com", false, true);
        b(region27, "data.iot", "data.iot.ap-southeast-3.amazonaws.com", false, true);
        b(region27, ServiceAbbreviations.f21134e, "dynamodb.ap-southeast-3.amazonaws.com", false, true);
        b(region27, ServiceAbbreviations.f21135f, "ec2.ap-southeast-3.amazonaws.com", false, true);
        b(region27, ServiceAbbreviations.f21151v, "elasticloadbalancing.ap-southeast-3.amazonaws.com", false, true);
        b(region27, "firehose", "firehose.ap-southeast-3.amazonaws.com", false, true);
        b(region27, "iot", "iot.ap-southeast-3.amazonaws.com", false, true);
        b(region27, "kinesis", "kinesis.ap-southeast-3.amazonaws.com", false, true);
        b(region27, "kms", "kms.ap-southeast-3.amazonaws.com", false, true);
        b(region27, "lambda", "lambda.ap-southeast-3.amazonaws.com", false, true);
        b(region27, "logs", "logs.ap-southeast-3.amazonaws.com", false, true);
        b(region27, "polly", "polly.ap-southeast-3.amazonaws.com", false, true);
        b(region27, "s3", "s3.ap-southeast-3.amazonaws.com", false, true);
        b(region27, ServiceAbbreviations.f21141l, "sdb.ap-southeast-3.amazonaws.com", false, true);
        b(region27, ServiceAbbreviations.f21142m, "sns.ap-southeast-3.amazonaws.com", false, true);
        b(region27, ServiceAbbreviations.f21143n, "sqs.ap-southeast-3.amazonaws.com", false, true);
        b(region27, ServiceAbbreviations.f21149t, "sts.ap-southeast-3.amazonaws.com", false, true);
        Region region28 = new Region("me-central-1", "amazonaws.com");
        arrayList.add(region28);
        b(region28, ServiceAbbreviations.f21145p, "autoscaling.me-central-1.amazonaws.com", false, true);
        b(region28, "cognito-identity", "cognito-identity.me-central-1.amazonaws.com", false, true);
        b(region28, "cognito-idp", "cognito-idp.me-central-1.amazonaws.com", false, true);
        b(region28, "cognito-sync", "cognito-sync.me-central-1.amazonaws.com", false, true);
        b(region28, "data.iot", "data.iot.me-central-1.amazonaws.com", false, true);
        b(region28, ServiceAbbreviations.f21134e, "dynamodb.me-central-1.amazonaws.com", false, true);
        b(region28, ServiceAbbreviations.f21135f, "ec2.me-central-1.amazonaws.com", false, true);
        b(region28, ServiceAbbreviations.f21151v, "elasticloadbalancing.me-central-1.amazonaws.com", false, true);
        b(region28, "firehose", "firehose.me-central-1.amazonaws.com", false, true);
        b(region28, "iot", "iot.me-central-1.amazonaws.com", false, true);
        b(region28, "kinesis", "kinesis.me-central-1.amazonaws.com", false, true);
        b(region28, "kms", "kms.me-central-1.amazonaws.com", false, true);
        b(region28, "lambda", "lambda.me-central-1.amazonaws.com", false, true);
        b(region28, "logs", "logs.me-central-1.amazonaws.com", false, true);
        b(region28, "polly", "polly.me-central-1.amazonaws.com", false, true);
        b(region28, "s3", "s3.me-central-1.amazonaws.com", false, true);
        b(region28, ServiceAbbreviations.f21141l, "sdb.me-central-1.amazonaws.com", false, true);
        b(region28, ServiceAbbreviations.f21142m, "sns.me-central-1.amazonaws.com", false, true);
        b(region28, ServiceAbbreviations.f21143n, "sqs.me-central-1.amazonaws.com", false, true);
        b(region28, ServiceAbbreviations.f21149t, "sts.me-central-1.amazonaws.com", false, true);
        Region region29 = new Region("ap-south-2", "amazonaws.com");
        arrayList.add(region29);
        b(region29, ServiceAbbreviations.f21145p, "autoscaling.ap-south-2.amazonaws.com", false, true);
        b(region29, "cognito-identity", "cognito-identity.ap-south-2.amazonaws.com", false, true);
        b(region29, "cognito-idp", "cognito-idp.ap-south-2.amazonaws.com", false, true);
        b(region29, "cognito-sync", "cognito-sync.ap-south-2.amazonaws.com", false, true);
        b(region29, "data.iot", "data.iot.ap-south-2.amazonaws.com", false, true);
        b(region29, ServiceAbbreviations.f21134e, "dynamodb.ap-south-2.amazonaws.com", false, true);
        b(region29, ServiceAbbreviations.f21135f, "ec2.ap-south-2.amazonaws.com", false, true);
        b(region29, ServiceAbbreviations.f21151v, "elasticloadbalancing.ap-south-2.amazonaws.com", false, true);
        b(region29, "firehose", "firehose.ap-south-2.amazonaws.com", false, true);
        b(region29, "iot", "iot.ap-south-2.amazonaws.com", false, true);
        b(region29, "kinesis", "kinesis.ap-south-2.amazonaws.com", false, true);
        b(region29, "kms", "kms.ap-south-2.amazonaws.com", false, true);
        b(region29, "lambda", "lambda.ap-south-2.amazonaws.com", false, true);
        b(region29, "logs", "logs.ap-south-2.amazonaws.com", false, true);
        b(region29, "polly", "polly.ap-south-2.amazonaws.com", false, true);
        b(region29, "s3", "s3.ap-south-2.amazonaws.com", false, true);
        b(region29, ServiceAbbreviations.f21141l, "sdb.ap-south-2.amazonaws.com", false, true);
        b(region29, ServiceAbbreviations.f21142m, "sns.ap-south-2.amazonaws.com", false, true);
        b(region29, ServiceAbbreviations.f21143n, "sqs.ap-south-2.amazonaws.com", false, true);
        b(region29, ServiceAbbreviations.f21149t, "sts.ap-south-2.amazonaws.com", false, true);
        Region region30 = new Region("ap-southeast-4", "amazonaws.com");
        arrayList.add(region30);
        b(region30, ServiceAbbreviations.f21145p, "autoscaling.ap-southeast-4.amazonaws.com", false, true);
        b(region30, "cognito-identity", "cognito-identity.ap-southeast-4.amazonaws.com", false, true);
        b(region30, "cognito-idp", "cognito-idp.ap-southeast-4.amazonaws.com", false, true);
        b(region30, "cognito-sync", "cognito-sync.ap-southeast-4.amazonaws.com", false, true);
        b(region30, "data.iot", "data.iot.ap-southeast-4.amazonaws.com", false, true);
        b(region30, ServiceAbbreviations.f21134e, "dynamodb.ap-southeast-4.amazonaws.com", false, true);
        b(region30, ServiceAbbreviations.f21135f, "ec2.ap-southeast-4.amazonaws.com", false, true);
        b(region30, ServiceAbbreviations.f21151v, "elasticloadbalancing.ap-southeast-4.amazonaws.com", false, true);
        b(region30, "firehose", "firehose.ap-southeast-4.amazonaws.com", false, true);
        b(region30, "iot", "iot.ap-southeast-4.amazonaws.com", false, true);
        b(region30, "kinesis", "kinesis.ap-southeast-4.amazonaws.com", false, true);
        b(region30, "kms", "kms.ap-southeast-4.amazonaws.com", false, true);
        b(region30, "lambda", "lambda.ap-southeast-4.amazonaws.com", false, true);
        b(region30, "logs", "logs.ap-southeast-4.amazonaws.com", false, true);
        b(region30, "polly", "polly.ap-southeast-4.amazonaws.com", false, true);
        b(region30, "s3", "s3.ap-southeast-4.amazonaws.com", false, true);
        b(region30, ServiceAbbreviations.f21141l, "sdb.ap-southeast-4.amazonaws.com", false, true);
        b(region30, ServiceAbbreviations.f21142m, "sns.ap-southeast-4.amazonaws.com", false, true);
        b(region30, ServiceAbbreviations.f21143n, "sqs.ap-southeast-4.amazonaws.com", false, true);
        b(region30, ServiceAbbreviations.f21149t, "sts.ap-southeast-4.amazonaws.com", false, true);
        Region region31 = new Region("il-central-1", "amazonaws.com");
        arrayList.add(region31);
        b(region31, ServiceAbbreviations.f21145p, "autoscaling.il-central-1.amazonaws.com", false, true);
        b(region31, "cognito-identity", "cognito-identity.il-central-1.amazonaws.com", false, true);
        b(region31, "cognito-idp", "cognito-idp.il-central-1.amazonaws.com", false, true);
        b(region31, "cognito-sync", "cognito-sync.il-central-1.amazonaws.com", false, true);
        b(region31, "data.iot", "data.iot.il-central-1.amazonaws.com", false, true);
        b(region31, ServiceAbbreviations.f21134e, "dynamodb.il-central-1.amazonaws.com", false, true);
        b(region31, ServiceAbbreviations.f21135f, "ec2.il-central-1.amazonaws.com", false, true);
        b(region31, ServiceAbbreviations.f21151v, "elasticloadbalancing.il-central-1.amazonaws.com", false, true);
        b(region31, "firehose", "firehose.il-central-1.amazonaws.com", false, true);
        b(region31, "iot", "iot.il-central-1.amazonaws.com", false, true);
        b(region31, "kinesis", "kinesis.il-central-1.amazonaws.com", false, true);
        b(region31, "kms", "kms.il-central-1.amazonaws.com", false, true);
        b(region31, "lambda", "lambda.il-central-1.amazonaws.com", false, true);
        b(region31, "logs", "logs.il-central-1.amazonaws.com", false, true);
        b(region31, "polly", "polly.il-central-1.amazonaws.com", false, true);
        b(region31, "s3", "s3.il-central-1.amazonaws.com", false, true);
        b(region31, ServiceAbbreviations.f21141l, "sdb.il-central-1.amazonaws.com", false, true);
        b(region31, ServiceAbbreviations.f21142m, "sns.il-central-1.amazonaws.com", false, true);
        b(region31, ServiceAbbreviations.f21143n, "sqs.il-central-1.amazonaws.com", false, true);
        b(region31, ServiceAbbreviations.f21149t, "sts.il-central-1.amazonaws.com", false, true);
        return arrayList;
    }

    private static void b(Region region, String str, String str2, boolean z5, boolean z6) {
        Map<String, String> i5 = region.i();
        Map<String, Boolean> c5 = region.c();
        Map<String, Boolean> d5 = region.d();
        i5.put(str, str2);
        c5.put(str, Boolean.valueOf(z5));
        d5.put(str, Boolean.valueOf(z6));
    }
}
