package com.google.android.gms.internal.ads;

import android.content.pm.ApplicationInfo;
import android.content.pm.PackageInfo;
import android.os.Bundle;
import android.os.Parcel;
import android.os.Parcelable;
import com.google.android.gms.ads.internal.util.client.VersionInfoParcel;
import com.google.android.gms.common.internal.safeparcel.AbstractSafeParcelable;
import j$.util.DesugarCollections;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

/* loaded from: classes3.dex */
public final class zzbuq extends AbstractSafeParcelable {
    public static final Parcelable.Creator<zzbuq> CREATOR = new zzbur();
    public final long zzA;
    public final String zzB;
    public final float zzC;
    public final int zzD;
    public final int zzE;
    public final boolean zzF;
    public final String zzG;
    public final boolean zzH;
    public final String zzI;
    public final boolean zzJ;
    public final int zzK;
    public final Bundle zzL;
    public final String zzM;
    public final com.google.android.gms.ads.internal.client.zzef zzN;
    public final boolean zzO;
    public final Bundle zzP;
    public final String zzQ;
    public final String zzR;
    public final String zzS;
    public final boolean zzT;
    public final List zzU;
    public final String zzV;
    public final List zzW;
    public final int zzX;
    public final boolean zzY;
    public final boolean zzZ;
    public final int zza;
    public final boolean zzaa;
    public final ArrayList zzab;
    public final String zzac;
    public final zzblz zzad;
    public final String zzae;
    public final Bundle zzaf;
    public final Bundle zzb;
    public final com.google.android.gms.ads.internal.client.zzm zzc;
    public final com.google.android.gms.ads.internal.client.zzs zzd;
    public final String zze;
    public final ApplicationInfo zzf;
    public final PackageInfo zzg;
    public final String zzh;
    public final String zzi;
    public final String zzj;
    public final VersionInfoParcel zzk;
    public final Bundle zzl;
    public final int zzm;
    public final List zzn;
    public final Bundle zzo;
    public final boolean zzp;
    public final int zzq;
    public final int zzr;
    public final float zzs;
    public final String zzt;
    public final long zzu;
    public final String zzv;
    public final List zzw;
    public final String zzx;
    public final zzbfl zzy;
    public final List zzz;

    zzbuq(int i11, Bundle bundle, com.google.android.gms.ads.internal.client.zzm zzmVar, com.google.android.gms.ads.internal.client.zzs zzsVar, String str, ApplicationInfo applicationInfo, PackageInfo packageInfo, String str2, String str3, String str4, VersionInfoParcel versionInfoParcel, Bundle bundle2, int i12, List list, Bundle bundle3, boolean z11, int i13, int i14, float f11, String str5, long j11, String str6, List list2, String str7, zzbfl zzbflVar, List list3, long j12, String str8, float f12, boolean z12, int i15, int i16, boolean z13, String str9, String str10, boolean z14, int i17, Bundle bundle4, String str11, com.google.android.gms.ads.internal.client.zzef zzefVar, boolean z15, Bundle bundle5, String str12, String str13, String str14, boolean z16, List list4, String str15, List list5, int i18, boolean z17, boolean z18, boolean z19, ArrayList arrayList, String str16, zzblz zzblzVar, String str17, Bundle bundle6) {
        this.zza = i11;
        this.zzb = bundle;
        this.zzc = zzmVar;
        this.zzd = zzsVar;
        this.zze = str;
        this.zzf = applicationInfo;
        this.zzg = packageInfo;
        this.zzh = str2;
        this.zzi = str3;
        this.zzj = str4;
        this.zzk = versionInfoParcel;
        this.zzl = bundle2;
        this.zzm = i12;
        this.zzn = list;
        this.zzz = list3 == null ? Collections.EMPTY_LIST : DesugarCollections.unmodifiableList(list3);
        this.zzo = bundle3;
        this.zzp = z11;
        this.zzq = i13;
        this.zzr = i14;
        this.zzs = f11;
        this.zzt = str5;
        this.zzu = j11;
        this.zzv = str6;
        this.zzw = list2 == null ? Collections.EMPTY_LIST : DesugarCollections.unmodifiableList(list2);
        this.zzx = str7;
        this.zzy = zzbflVar;
        this.zzA = j12;
        this.zzB = str8;
        this.zzC = f12;
        this.zzH = z12;
        this.zzD = i15;
        this.zzE = i16;
        this.zzF = z13;
        this.zzG = str9;
        this.zzI = str10;
        this.zzJ = z14;
        this.zzK = i17;
        this.zzL = bundle4;
        this.zzM = str11;
        this.zzN = zzefVar;
        this.zzO = z15;
        this.zzP = bundle5;
        this.zzQ = str12;
        this.zzR = str13;
        this.zzS = str14;
        this.zzT = z16;
        this.zzU = list4;
        this.zzV = str15;
        this.zzW = list5;
        this.zzX = i18;
        this.zzY = z17;
        this.zzZ = z18;
        this.zzaa = z19;
        this.zzab = arrayList;
        this.zzac = str16;
        this.zzad = zzblzVar;
        this.zzae = str17;
        this.zzaf = bundle6;
    }

    @Override // android.os.Parcelable
    public final void writeToParcel(Parcel parcel, int i11) {
        int i12 = this.zza;
        int a11 = xg.a.a(parcel);
        xg.a.s(parcel, 1, i12);
        xg.a.j(parcel, 2, this.zzb, false);
        xg.a.B(parcel, 3, this.zzc, i11, false);
        xg.a.B(parcel, 4, this.zzd, i11, false);
        xg.a.D(parcel, 5, this.zze, false);
        xg.a.B(parcel, 6, this.zzf, i11, false);
        xg.a.B(parcel, 7, this.zzg, i11, false);
        xg.a.D(parcel, 8, this.zzh, false);
        xg.a.D(parcel, 9, this.zzi, false);
        xg.a.D(parcel, 10, this.zzj, false);
        xg.a.B(parcel, 11, this.zzk, i11, false);
        xg.a.j(parcel, 12, this.zzl, false);
        xg.a.s(parcel, 13, this.zzm);
        xg.a.F(parcel, 14, this.zzn);
        xg.a.j(parcel, 15, this.zzo, false);
        xg.a.g(parcel, 16, this.zzp);
        xg.a.s(parcel, 18, this.zzq);
        xg.a.s(parcel, 19, this.zzr);
        xg.a.p(parcel, 20, this.zzs);
        xg.a.D(parcel, 21, this.zzt, false);
        xg.a.w(parcel, 25, this.zzu);
        xg.a.D(parcel, 26, this.zzv, false);
        xg.a.F(parcel, 27, this.zzw);
        xg.a.D(parcel, 28, this.zzx, false);
        xg.a.B(parcel, 29, this.zzy, i11, false);
        xg.a.F(parcel, 30, this.zzz);
        xg.a.w(parcel, 31, this.zzA);
        xg.a.D(parcel, 33, this.zzB, false);
        xg.a.p(parcel, 34, this.zzC);
        xg.a.s(parcel, 35, this.zzD);
        xg.a.s(parcel, 36, this.zzE);
        xg.a.g(parcel, 37, this.zzF);
        xg.a.D(parcel, 39, this.zzG, false);
        xg.a.g(parcel, 40, this.zzH);
        xg.a.D(parcel, 41, this.zzI, false);
        xg.a.g(parcel, 42, this.zzJ);
        xg.a.s(parcel, 43, this.zzK);
        xg.a.j(parcel, 44, this.zzL, false);
        xg.a.D(parcel, 45, this.zzM, false);
        xg.a.B(parcel, 46, this.zzN, i11, false);
        xg.a.g(parcel, 47, this.zzO);
        xg.a.j(parcel, 48, this.zzP, false);
        xg.a.D(parcel, 49, this.zzQ, false);
        xg.a.D(parcel, 50, this.zzR, false);
        xg.a.D(parcel, 51, this.zzS, false);
        xg.a.g(parcel, 52, this.zzT);
        xg.a.u(parcel, 53, this.zzU);
        xg.a.D(parcel, 54, this.zzV, false);
        xg.a.F(parcel, 55, this.zzW);
        xg.a.s(parcel, 56, this.zzX);
        xg.a.g(parcel, 57, this.zzY);
        xg.a.g(parcel, 58, this.zzZ);
        xg.a.g(parcel, 59, this.zzaa);
        xg.a.F(parcel, 60, this.zzab);
        xg.a.D(parcel, 61, this.zzac, false);
        xg.a.B(parcel, 63, this.zzad, i11, false);
        xg.a.D(parcel, 64, this.zzae, false);
        xg.a.j(parcel, 65, this.zzaf, false);
        xg.a.b(parcel, a11);
    }
}
